### ISSUE TITLE
[FEATURE] Update Ignition version to include 8.1.23 and 8.1.24

### ISSUE THREAD

**Issue by etknorr** [design-group/ignition-docker-legacy#51]
**Issue**
Newer versions of Ignition docker have been released by Inductive but this image has not been updated.

**Solution**
Update this project to include the latest releases of Ignition Docker. (Unless you beat me to it, I'm going to try to bump these myself)

**Comment by keith-gamble** [comment]
I have not started this at all, should be fairly straight forward just need to change the bake file. However for the IIoT images you will also need to get the checksums and URLs for the latest modules.

**Comment by etknorr** [comment]
Fixed here (#52)
